apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: gcs
    config:
      bucket: <bucket_name>
      service_account: |-
        {
          "type": "external_account",
          "audience": "//iam.googleapis.com/projects/1073045085223/locations/global/workloadIdentityPools/obs-idpool/providers/obs-awsprovider",
          "subject_token_type": "urn:ietf:params:aws:token-type:aws4_request",
          "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/obs-sc-acm28@gc-acm-test.iam.gserviceaccount.com:generateAccessToken",
          "token_url": "https://sts.googleapis.com/v1/token",
          "credential_source": {
            "environment_id": "aws1",
            "region_url": "http://169.254.169.254/latest/meta-data/placement/availability-zone",
            "url": "http://169.254.169.254/latest/meta-data/iam/security-credentials",
            "regional_cred_verification_url": "https://sts.{region}.amazonaws.com?Action=GetCallerIdentity&Version=2011-06-15"
          }
        }